---
# Define a list of resources that the robot needs to register when passing.
- resource_id: "R01"  # Should match the resource ID used by the resource management server
  floor_id: "1F"  # Should match the level name used by Open-RMF
  center_x: 0.0
  center_y: 0.0
